[package]
name = "rix-core"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2021"

[dependencies]
rix-util = { path = "../util" }

anyhow = "1.0.42"
bincode = "1.3.3"
codespan = "0.11.1"
derive_more = "0.99.16"
dirs = "4.0.0"
enum-as-inner = "0.3.3"
itertools = "0.10.1"
lalrpop-util = "0.19.6"
lazy_static = "1.4.0"
parking_lot = "0.11.1"
path_abs = "0.5.1"
regex = "1.5.4"
serde = { version = "1.0.127", features = ["rc", "derive"] }
slog-scope = "4.4.0"
smallvec = "1.6.1"
strum = { version = "0.23.0", features = ["derive"] }
thiserror = "1.0.26"

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"

[build-dependencies]
lalrpop = "0.19.6"
