[package]
name = "rix-core"
version = "0.1.0"
authors = ["Jude Taylor <me@jude.xyz>"]
edition = "2021"

[dependencies]
enum-as-inner = "0.3.3"
parking_lot = "0.11.2"
rix-syntax = { path = "../syntax" }
rix-util = { path = "../util" }
slog-scope = "4.4.0"
smallvec = "1.7.0"

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"

[build-dependencies]
lalrpop = "0.19.6"
